### ISSUE TITLE
Error running in XCode: Build Failed

### ISSUE THREAD

**Issue by elie222** [spencercarli/meteor-react-native-authentication#1]
Getting a Build Failed error due to:
meteor-react-native-authentication/RNApp/ios/RNApp/AppDelegate.m:12:9: 'RCTRootView.h' file not found

**Comment by elie222** [comment]
Made a pull request to fix this:
https://github.com/spencercarli/meteor-react-native-authentication/pull/2

Was missing the `npm install` command in the README

**Comment by spencercarli** [comment]
closed via 94610251d73885a41eb25238f4d4b212d868a838
